language: node_js
node_js:
  - "0.10"
addons:
  firefox: "25.0"
before_install:
  - npm install -g grunt-cli
notifications:
  webhooks:
    urls:
      - secure: "v5qUk/Zl6w9wJKkjtmCZahLPVo/PaJ3LloFsCD2Lzhy08lR2RrC1SRixHdElEYpHk/KipBGAW/AwwLglvMjWmQsABA++TvbEoeb5KlWOouRFMvADbP4zHYvGx/gJGcFW+djsdMexHb4FTUtYfEyDpEC00FTUPbyOdxu6p00cJCY="
    on_success: always
    on_failure: always
    on_start: true